### ISSUE TITLE
This project works under msys2(Windows), so I think the homepage can be updated

### ISSUE THREAD

**Issue by asmwarrior** [coin3d/sowx#4]
As we discussed here: [In the cmakefile.txt, there is a library named SoWx, where can I find it? · Issue #2 · famorcia/wxSceneViewer](https://github.com/famorcia/wxSceneViewer/issues/2)

So, I think the homepage should be updated, Currently it only mention the visual studio under Windows.

In-fact, building under msys2 is much simple, as a lot of libraries are already supplied by the msys2 project. (can be installed by the pacman command in msys2's shell)

**Comment by famorcia** [comment]
Thanks a lor for your feedback. Homepage has been updated as suggested.
Regards
